# Generated by Django 3.0.8 on 2020-07-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=300)),
                ('book_image', models.ImageField(upload_to='book_images/')),
                ('author', models.CharField(blank=True, max_length=300)),
                ('date', models.DateTimeField()),
                ('location', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
