# Generated by Django 3.0.8 on 2020-07-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerBooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
            preserve_default=False,
        ),
    ]
