# Generated by Django 3.0.8 on 2020-07-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerBooks', '0004_remove_register_book_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_book',
            name='book_image',
            field=models.ImageField(blank=True, upload_to='models/'),
        ),
    ]
