# Generated by Django 3.0.8 on 2020-07-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerBooks', '0005_register_book_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_book',
            name='book_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
